app/Http/Controllers/Dashboard/FormController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\UpdateFormRequest;
use App\Site;
use App\Form;
use App\FormField;
use App\FormHelpers\FetchForms;
use App\HtmlForm;
use App\UrlTarget\UrlTarget;
use App\Http\Requests\StoreFormRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use mjanssen\BreadcrumbsBundle\Breadcrumbs;

class FormController extends Controller
{
    /**
     * Show all forms from this user
     *
     * @param  Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $forms = $request->user()->forms()->where('site_id', $request->user()->currentSite())->withCount(['sessions'])->orderBy('status', 'DESC')->orderBy('created_at', 'DESC')->get();
        $urlTargets = UrlTarget::getUrlTargets();

        Breadcrumbs::addBreadcrumb(__('Formulieren'), route('form.index'));

        return view('backend.form.index')->with(compact('forms', 'urlTargets'));
    }

    /**
     * View a form
     *
     * @param  Request $request
     * @param  Form    $form
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function view(Request $request, Form $form)
    {
        if (!$request->user()->can('view', $form) || $form->sessions()->count() === 0) {
            return redirect()->route('form.index');
        }

        Breadcrumbs::addBreadcrumb(__('Formulieren'), route('form.index'));
        Breadcrumbs::addBreadcrumb(__('Formulier \':form\'', ['form' => $form->title]), route('form.view', $form->id));

        $fields = $form->fields()->orderBy('sort_order', 'ASC')->get();
        foreach ($fields as $field) {
            $field->results = $field->getResults();
        }

        $formResults = $form->getResults();

        return view('backend.form.view')->with(compact('form', 'fields', 'formResults'));
    }

    /**
     * Add new form
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        Breadcrumbs::addBreadcrumb(__('Formulieren'), route('form.index'));
        Breadcrumbs::addBreadcrumb(__('Formulier toevoegen'), route('form.create'));

        $urlTargets = UrlTarget::getUrlTargets();

        return view('backend.form.create')->with(compact('urlTargets'));
    }

    /**
     * Store a form
     *
     * @param  StoreFormRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreFormRequest $request)
    {
        //get form from temporary table
        if (!$htmlForm = HtmlForm::where('id', $request->selected_form)->where('site_id', $request->user()->currentSite())->first()) {
            return redirect()->back()->withInput();
        }

        //create new form
        $form = (new Form)->fill(
            [
            'site_id' => $request->user()->currentSite(),
            'title' => $request->title,
            'url_target' => $request->url_target,
            'url_target_type' => $request->url_target_type
            ]
        );

        //add platforms
        foreach (['mobile', 'tablet', 'desktop'] as $platform) {
            $key = $platform.'_platform';
            $form->$key = in_array($platform, $request->platforms) && hasPermission($key);
        }

        //determine selector
        //TODO: one day we'll add custom selector tag like surve-form-name="form-name"
        if ($htmlForm->html_id <> null) {
            $form->selector_target_type = "id";
            $form->selector_target = $htmlForm->html_id;
        } else {
            $form->selector_target_type = "path";
            $form->selector_target = base64_decode($htmlForm->path);
        }

        //save form
        $form->save();

        //add fields to form
        $fields = json_decode($htmlForm->fields, true);
        $position = 0;
        foreach ($fields as $field) {
            (new FormField)->fill(
                [
                'form_id' => $form->id,
                'type' => $field['type'],
                'selector' => (isset($field['id']) ? 'id' : 'name'),
                'selector_value' => (isset($field['id']) ? $field['id'] : $field['name']),
                'title' => ucfirst(isset($field['label']) ? $field['label'] : (isset($field['placeholder']) ? $field['placeholder'] : (isset($field['name']) ? $field['name'] : $field['id']))),
                'sort_order' => $position
                ]
            )->save();

            $position++;
        }

        //success
        flashMessage(__('Formulier toegevoegd'), __('Het formulier is succesvol toegevoegd, om te beginnen met het verzamelen van informatie dient u hem te activeren.'));
        return redirect()->route('form.index');
    }


    /**
     * Edit a form
     *
     * @param  Request $request
     * @param  Form    $form
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function edit(Request $request, Form $form)
    {
        if (!$request->user()->can('update', $form)) {
            return redirect()->route('form.index');
        }

        //get platforms & targets
        $platforms = [($form->desktop_platform === true ? 'desktop' : ''), ($form->tablet_platform === true ? 'tablet' : ''), ($form->mobile_platform === true ? 'mobile' : '')];
        $urlTargets = UrlTarget::getUrlTargets();

        Breadcrumbs::addBreadcrumb(__('Formulieren'), route('form.index'));
        Breadcrumbs::addBreadcrumb(__('Formulier wijzigen'), route('form.edit', $form->id));

        return view('backend.form.edit')->with(compact('form', 'platforms', 'urlTargets'));
    }

    /**
     * Save updated form
     *
     * @param  UpdateFormRequest $request
     * @param  Form              $form
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateFormRequest $request, Form $form)
    {
        if (!$request->user()->can('update', $form)) {
            return redirect()->route('form.index');
        }

        //save
        $form->fill(
            [
            'title' => $request->title,
            'url_target' => $request->url_target,
            'url_target_type' => $request->url_target_type
            ]
        );

        //add platforms
        foreach (['mobile', 'tablet', 'desktop'] as $platform) {
            $key = $platform.'_platform';
            $form->$key = in_array($platform, $request->platforms) && hasPermission($key);
        }
        $form->save();

        //reset the cache for this site
        $form->site()->first()->invalidateCache();

        //success
        flashMessage(__('Formulier gewijzigd'), __('Het formulier is succesvol aangepast.'));
        return redirect()->route('form.index');
    }

    /**
     * Toggle form
     *
     * @param  Request $request
     * @param  Form    $form
     * @return \Illuminate\Http\RedirectResponse
     */
    public function toggle(Request $request, Form $form)
    {
        if (!$request->user()->can('toggle', $form)) {
            return redirect()->route('form.index');
        }

        //toggle heatmap
        if ($form->status === false) {
            //check if we can activate
            if (hasPermission('forms') > Site::find($request->user()->currentSite())->forms()->where('status', true)->count()) {
                //activate
                $form->status = true;

                flashMessage(__('Formulier geactiveerd'), __('Uw formulier is geactiveerd, binnen 10 minuten wordt de dataverzameling op uw website gestart.'));
            } else {
                $form->status = false;

                flashMessage(__('Formulier niet geactiveerd'), __('Uw formulier is niet geactiveerd, u heeft al het maximale aantal geactiveerd dat uw pakket toelaat.'), 'error');
            }
        } else {
            //de-activate
            $form->status = false;

            //calculate active time and add to active time
            $form->seconds_active += (time() - $form->last_status_change);

            flashMessage(__('Formulier gedeactiveerd'), __('Uw formulier is gedeactiveerd.'));
        }

        //save
        $form->last_status_change = time();
        $form->save();

        //reset the cache for this site
        $form->site()->first()->invalidateCache();

        return redirect()->route('form.index');
    }

    /**
     * Delete a form
     *
     * @param  Request $request
     * @param  Form    $form
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function delete(Request $request, Form $form)
    {
        if (!$request->user()->can('delete', $form)) {
            return redirect()->route('form.index');
        }

        //delete form
        $form->deleteComplete();

        flashMessage(__('Formulier verwijderd'), __('Uw formulier is verwijderd, alle bijhorende gegevens zijn eveneens verwijderd.'));

        //reset the cache for this site
        $form->site()->first()->invalidateCache();

        return redirect()->route('form.index');
    }


    /**
     * Reset sessions
     *
     * @param  Request $request
     * @param  Form    $form
     * @return \Illuminate\Http\RedirectResponse
     */
    public function reset(Request $request, Form $form)
    {
        if (!$request->user()->can('delete', $form)) {
            return redirect()->route('form.index');
        }

        //delete form sessions
        $form->deleteSessions();

        flashMessage(__('Sessies verwijderd'), __('Uw sessies zijn verwijderd, het formulier begint opnieuw met data verzamelen.'));

        return redirect()->route('form.index');
    }

    /**
     * Process Ajax save function, returns errors with 422 or success with 200
     *
     * @param  StoreFormRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function ajaxSave(StoreFormRequest $request)
    {

resources/views/backend/form/create.blade.php
@extends('backend.layouts.app')

@section('content')
    <div class="container-fluid pt-25">
        <div class="row">
            <div class="col-md-12">
                <h5 class="mb-20">{{ __('Nieuw formulier') }}</h5>
                <div class="form-wrap" style="max-width: 800px;">
                    @include('backend.parts.errors')

                    <form method="post" action="{{ route('form.create') }}" id="app">
                        @csrf

                        <div class="form-group">
                            <label class="control-label mb-5 text-left" for="title">{{ __('Titel') }}</label>
                            <input class="form-control" value="{{ old('title') }}" id="title" name="title">
                            <span class="invalid-feedback" id="error_title">{{ $errors->first('title') }}</span>
                        </div>

                        <form-identification v-bind:modalroute="{{ json_encode(['url' => route('modal', 'identify-a-form')]) }}"></form-identification>
                        <span class="invalid-feedback" id="error_selected_form">{{ $errors->first('selected_form') }}</span>

                        <div class="form-group mt-20 mb-15">
                            <label class="block control-label mb-5 text-left">{{ __('Verzamel locaties') }}</label>
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <input type="hidden" id="url_target_type" name="url_target_type" value="{{ old('url_target_type', 'simple') }}" />
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span id="url_target_text">{{ $urlTargets[old('url_target_type', 'simple')]->getSettings()['title'] }}</span> <span class="caret"></span></button>
                                    <ul class="dropdown-menu info-buttons">
                                        @foreach ($urlTargets as $type => $urlTarget)
                                            <li>
                                                <a href="javascript:void(0)" class="url-target-link" data-value="{{ $type }}" data-text="{{ $urlTarget->getSettings()['title'] }}">
                                                    {{ $urlTarget->getSettings()['title'] }}
                                                </a>
                                                <a href="{{ route('modal', 'url-targets') }}" data-toggle="modal" class="info-icon"><i class="fa fa-info-circle"></i></a>
                                            </li>
                                        @endforeach
                                    </ul>
                                </div>
                                <input type="text" id="url_target" name="url_target" value="{{ old('url_target') }}" class="form-control" placeholder="{{ __('bijv. https://www.voorbeeld.nl') }}">
                            </div>
                            <span class="invalid-feedback" id="error_url_target">{{ $errors->first('url_target') }}</span>
                        </div>

                        <div class="form-group no-margin-switcher">
                            <label class="block control-label mb-5 text-left" for="name">{{ __('Platforms') }}</label>
                            <label class="block mb-10" @if (hasPermission('desktop_platform') === false) style="color: #8f8d8d;" @else style="color: #555;" @endif>
                                <input class="js-switch" data-color="#4aa23c" type="checkbox" name="platforms[]" value="desktop"
                                    @if (hasPermission('desktop_platform') === false)
                                        disabled
                                    @endif
                                    @if (is_array(old('platforms')) && in_array('desktop', old('platforms')))
                                        checked
                                    @endif  /> {{ __('Desktop') }}
                                @if (hasPermission('desktop_platform') === false) @include('backend.parts.upgrade') @endif
                            </label>
                            <label class="block mb-10" @if (hasPermission('tablet_platform') === false) style="color: #8f8d8d;" @else style="color: #555;" @endif>
                                <input class="js-switch js-mobile-platform" data-color="#4aa23c" type="checkbox" name="platforms[]" value="tablet"
                                    @if (hasPermission('tablet_platform') === false)
                                        disabled
                                    @endif
                                    @if (is_array(old('platforms')) && in_array('tablet', old('platforms')))
                                        checked
                                    @endif  /> {{ __('Tablet') }}
                                @if (hasPermission('tablet_platform') === false) @include('backend.parts.upgrade') @endif
                            </label>
                            <label class="block" @if (hasPermission('mobile_platform') === false) style="color: #8f8d8d;" @else style="color: #555;" @endif>
                                <input class="js-switch js-mobile-platform" data-color="#4aa23c" type="checkbox" name="platforms[]" value="mobile"
                                    @if (hasPermission('mobile_platform') === false)
                                        disabled
                                    @endif
                                    @if (is_array(old('platforms')) && in_array('mobile', old('platforms')))
                                        checked
                                    @endif />
                                {{ __('Mobiel') }}
                                @if (hasPermission('mobile_platform') === false) @include('backend.parts.upgrade') @endif
                            </label>
                            <span class="invalid-feedback" id="error_platforms">{{ $errors->first('platforms') }}</span>
                        </div>

                        <div class="form-group mb-0 mt-15">
                            <button class="btn btn-primary js-submit-button">{{ __('Toevoegen') }} <span class="form-loader js-form-loader"><i class="fa fa-spinner fa-spin"></i></span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="/assets/backend/js/vue/app.js"></script>
    <script>
        const fields = ['title', 'selected_form', 'platforms', 'url_target'];
        let can_submit = false;

        //set laravel csrf token in header
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        //on submit send form
        //TODO: make global function to use on all pages
        $('#app').on('submit', function(e) {
            //submit this form
            if (can_submit === true) {
                return true;
            }

            //prevent submit
            e.preventDefault();

            //show loading screen
            startLoading();

            //check results
            $.ajax({
                type: "POST",
                url: '{{ route('form.save') }}',
                data: $(this).serialize(),
                statusCode: {
                    //errors in input
                    422: function(xhr) {
                        const result = JSON.parse(xhr.responseText);
                        const errors = Object.entries(result.errors);

                        //reset error messages
                        fields.map(function(field) {
                            $('#error_' + field).html('');
                        });

                        errors.map(function(error) {
                            $('#error_' + error[0]).show().html(error[1][0]);
                        });

                        endLoading();
                    }
                },
                //success, redirect user
                success: function(result) {
                    if (result.message === 'success') {
                        can_submit = true;
                        $('#app').submit();
                    }

                    endLoading();
                }
            });
        });

        //start loading
        function startLoading() {
            $('.js-form-loader').show();
            $('.js-submit-button').attr('disabled', 'disabled');
        }

        //end loading //TODO: move to general spot
        function endLoading() {
            $('.js-form-loader').hide();
            $('.js-submit-button').removeAttr('disabled');
        }
    </script>
    <script>
        $('.url-target-link').on('click', function() {
            $("#url_target_text").html($(this).data('text'));
            $("#url_target_type").val($(this).data('value'));
        });
    </script>
@endsection

resources/views/backend/form/index.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="container-fluid pt-25">
    <div class="row">
        <div class="col-md-12">
            <h5 class="mb-20">{{ __('Formulieren') }}</h5>
            @if (count($forms) > 0)
                <div class="table-wrap">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>{{ __('ID') }}</th>
                                <th>{{ __('Naam') }}</th>
                                <th>{{ __('Sessies') }}</th>
                                <th>{{ __('Status') }}</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($forms as $form)
                                <tr>
                                    <td>{{ $form->id }}</td>
                                    <td>
                                        <a href="{{ route('form.edit', $form->id) }}">{{ $form->title }}</a><br />
                                    </td>
                                    <td>
                                        {{ __(':count/:max', ['count' => thousand($form->sessions_count), 'max' => thousand(\App\SubscriptionManager\SubscriptionManager::instance()->option('max_form_views')->allowed_usage)]) }}
                                        <a href="{{ route('modal', 'form-sessions') }}" data-toggle="modal"><i class="fa fa-info-circle ml-5"></i></a>
                                    </td>
                                    <td><a href="{{ route('form.toggle', $form->id) }}">
                                            @if ($form->status === true)
                                                <span class="label label-primary">{{ __('Actief') }}</span>
                                            @else
                                                <span class="label label-default">{{ __('In-actief') }}</span>
                                            @endif
                                        </a>
                                    </td>
                                    <td>
                                        <div class="pull-right">
                                            @if ($form->sessions_count === 0)
                                                <a class="action action-button mr-10" href="{{ route('modal', 'form-has-no-views') }}" data-toggle="modal"><i class="fa fa-clipboard-check"></i></a>
                                            @else
                                                <a class="action action-button mr-10" href="{{ route('form.view', $form->id) }}"><i class="fa fa-clipboard-check"></i></a>
                                            @endif
                                            <a class="action action-button mr-10" href="{{ route('form.edit', $form->id) }}"><i class="fa fa-edit"></i></a>
                                            <a class="action action-button delete" data-toggle="modal" href="{{ route('modal', ['type' => 'form-delete', 'id' => $form->id]) }}"><i class="fa fa-trash-alt"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            @else
                <div style="max-width: 800px;">
                    <p class="mb-20">
                        {{ __('Met formulieren krijgt u een uitgebreide analyse van de formulieren op uw website. Zo ziet u hoe uw bezoekers zich gedragen wanneer ze een formulier invullen.') }}
                        {{ __('De informatie die u hieruit haalt kunt u direct inzetten om blokkerende factoren in uw conversiefunnel te verwijderen.') }}
                    </p>
                    <p style="text-align: center;">
                        <a class="btn btn-primary" href="{{ route('form.create') }}">{{ __('Beginnen met formulieren') }} <i class="fa fa-clipboard-list ml-10"></i> </a>
                    </p>

                    <div class="row mb-30 mt-30" style="background: #f6f6f6; padding: 15px 0;">
                        <div class="col-md-6 col-xs-12 pull-right">
                            <img src="/assets/backend/images/icons/scroll-heatmaps.png" class="img-responsive" style="max-height: 170px; margin: 0 auto;" />
                            <p class="visible-xs">&nbsp;</p>
                        </div>
                        <div class="col-md-6 col-xs-12">
                            <h5>{{ __('Conversiepercentage') }}</h5>
                            <p class="mb-10">{{ __('Uw formulieren zijn vaak een belangrijk punt van uw website. Hier komen de leads binnen die geld opleveren. Hoe hoger uw conversiepercentage, des te meer omzet. Gebruik de formulieranalyses om uw conversiepercentage te meten en te verbeteren.') }}</p>
                        </div>
                    </div>
                    <div class="row mb-30">
                        <div class="col-md-6 col-xs-12 pull-left">
                            <img src="/assets/backend/images/icons/move-heatmaps.png" class="img-responsive" style="max-height: 170px; margin: 0 auto;" />
                            <p class="visible-xs">&nbsp;</p>
                        </div>
                        <div class="col-md-6 col-xs-12">
                            <h5>{{ __('Optimale formuliervelden') }}</h5>
                            <p class="mb-10">{{ __('Identificeer de velden in een formulier waarop uw bezoekers vastlopen of afhaken. Verwijder velden of maak deze optioneel en meet het effect. Zo wordt uw gebruiksvriendelijkheid voor bezoekers eenvoudig hoger en zal ook uw conversie toenemen.') }}</p>
                        </div>
                    </div>
                    <div class="row mb-30" style="background: #f6f6f6; padding: 15px 0;">
                        <div class="col-md-6 col-xs-12 pull-right">
                            <img src="/assets/backend/images/icons/click-heatmaps.png" class="img-responsive" style="max-height: 170px; margin: 0 auto;" />
                            <p class="visible-xs">&nbsp;</p>
                        </div>
                        <div class="col-md-6 col-xs-12">
                            <h5>{{ __('Platformspecifieke optimalisatie') }}</h5>
                            <p class="mb-10">{{ __('Van elke formuliersessie wordt het platform geregistreerd. Zo kunt u optimaliseren door op mobiel een ander formulier te tonen dan op desktop sessies. Hiermee kunt u de gebruikesvriendelijkheid voor uw mobiele bezoekers optimaliseren.') }}</p>
                        </div>
                    </div>
                </div>
            @endif
            <a class="btn btn-primary" href="{{ route('form.create') }}"><i class="fa fa-plus mr-10"></i> {{ __('Formulier toevoegen') }}</a>
        </div>
    </div>
</div>
@endsection